const products = [
  {
    id: 1,
    title: "Logitech G502 HERO Wired Gaming Mouse",
    image: "https://m.media-amazon.com/images/I/61mpMH5TzkL._AC_SL1500_.jpg",
    price: 49.99,
    rate: 4.8,
    category: "gaming accessories",
  },
  {
    id: 2,
    title: "Corsair K95 RGB Mechanical Gaming Keyboard",
    image: "https://m.media-amazon.com/images/I/713zUjb6nIL._AC_SL1200_.jpg",
    price: 129.99,
    rate: 4.7,
    category: "gaming accessories",
  },
  {
    id: 3,
    title: "Razer BlackShark V2 Pro Wireless Headset",
    image: "https://m.media-amazon.com/images/I/71mzxWaotaL._AC_SL1500_.jpg",
    price: 99.99,
    rate: 4.6,
    category: "gaming accessories",
  },
  {
    id: 4,
    title: "SteelSeries QcK Gaming Mouse Pad",
    image: "https://m.media-amazon.com/images/I/31s5e601Y+L._AC_SX679_.jpg",
    price: 14.99,
    rate: 4.7,
    category: "gaming accessories",
  },
  {
    id: 5,
    title: "Elgato Stream Deck Mini",
    image: "https://m.media-amazon.com/images/I/61lMOu6N8lL._AC_SX522_.jpg",
    price: 79.99,
    rate: 4.8,
    category: "gaming accessories",
  },
  {
    id: 6,
    title: "Dell XPS 13 Laptop (12th Gen, 16GB RAM)",
    image: "https://m.media-amazon.com/images/I/31acHDJ02eL._AC_SX679_.jpg",
    price: 999.99,
    rate: 4.5,
    category: "computers & accessories",
  },
  {
    id: 7,
    title: 'HP 27" Full HD Monitor',
    image: "https://m.media-amazon.com/images/I/81ydcNJTzfS._AC_SX679_.jpg",
    price: 179.99,
    rate: 4.4,
    category: "computers & accessories",
  },
  {
    id: 8,
    title: "Logitech MX Master 3S Wireless Mouse",
    image: "https://m.media-amazon.com/images/I/512V4kRs2iL._AC_SX522_.jpg",
    price: 99.99,
    rate: 4.8,
    category: "computers & accessories",
  },
  {
    id: 9,
    title: "Anker USB C Hub, PowerExpand 8-in-1",
    image:
      "https://m.media-amazon.com/images/I/51Gv5-7oTnL.__AC_SX300_SY300_QL70_ML2_.jpg",
    price: 59.99,
    rate: 4.6,
    category: "computers & accessories",
  },
  {
    id: 10,
    title: "Samsung T7 Portable SSD 1TB",
    image: "https://m.media-amazon.com/images/I/91YfRIy7kYL._AC_SX679_.jpg",
    price: 109.99,
    rate: 4.7,
    category: "computers & accessories",
  },

  // Holiday Deals
  {
    id: 11,
    title: "Smart LED Strip Lights with App Control",
    image: "https://m.media-amazon.com/images/I/516vweRJ0NL._AC_.jpg",
    price: 25.99,
    rate: 4.3,
    category: "holiday deals",
  },
  {
    id: 12,
    title: "Mini Projector for Home Theater",
    image: "https://m.media-amazon.com/images/I/61ETmo-oOaL._AC_SX522_.jpg",
    price: 89.99,
    rate: 4.2,
    category: "holiday deals",
  },
  {
    id: 13,
    title: "Portable Bluetooth Speaker with Lights",
    image: "https://m.media-amazon.com/images/I/61zCadF9RcL._AC_SX522_.jpg",
    price: 39.99,
    rate: 4.6,
    category: "holiday deals",
  },
  {
    id: 14,
    title: "Holiday Scented Candle Set",
    image: "https://m.media-amazon.com/images/I/815lwLQlweL._AC_SX679_.jpg",
    price: 19.99,
    rate: 4.5,
    category: "holiday deals",
  },
  {
    id: 15,
    title: "Festive String Lights for Decoration",
    image: "https://m.media-amazon.com/images/I/61+YO6R2JWL._AC_SX679_.jpg",
    price: 15.99,
    rate: 4.4,
    category: "holiday deals",
  },
  {
    id: 16,
    title: "Razer Kraken X Ultralight Gaming Headset",
    image: "https://m.media-amazon.com/images/I/51FRJHB7XOL._AC_SX522_.jpg",
    price: 44.99,
    rate: 4.5,
    category: "gaming accessories",
  },
  {
    id: 17,
    title: "Redragon K552 Mechanical Gaming Keyboard",
    image:
      "https://m.media-amazon.com/images/I/710omcTgKEL.__AC_SX300_SY300_QL70_ML2_.jpg",
    price: 39.99,
    rate: 4.6,
    category: "gaming accessories",
  },

  // Computers & Accessories
  {
    id: 18,
    title: "Seagate Portable 2TB External Hard Drive",
    image: "https://m.media-amazon.com/images/I/510+J06fz0L._AC_SX679_.jpg",
    price: 62.99,
    rate: 4.7,
    category: "computers & accessories",
  },
  {
    id: 20,
    title: "TP-Link WiFi 6 Router AX1800",
    image: "https://m.media-amazon.com/images/I/41kHxeOdw+L._AC_SX679_.jpg",
    price: 79.99,
    rate: 4.5,
    category: "computers & accessories",
  },

  // Holiday Deals
  {
    id: 21,
    title: "Christmas Tree Tabletop Decoration",
    image: "https://m.media-amazon.com/images/I/71YXDc6BOeL._AC_SX679_.jpg",
    price: 22.49,
    rate: 4.4,
    category: "holiday deals",
  },
  {
    id: 22,
    title: "Holiday Cookie Cutter Set – 30 Pieces",
    image: "https://m.media-amazon.com/images/I/71UCdbrq5JL._AC_SX679_.jpg",
    price: 14.99,
    rate: 4.6,
    category: "holiday deals",
  },
  {
    id: 23,
    title: "Holiday Themed Throw Blanket – Soft Plush",
    image: "https://m.media-amazon.com/images/I/51-E4VavbeL._AC_SX679_.jpg",
    price: 27.95,
    rate: 4.8,
    category: "holiday deals",
  },
  {
    id: 24,
    title: "LED Flameless Candles Set – Battery Operated",
    image: "https://m.media-amazon.com/images/I/61N8xC9woKL._AC_SX679_.jpg",
    price: 29.99,
    rate: 4.7,
    category: "holiday deals",
  },
  // Home Gadgets
  {
    id: 25,
    title: "Echo Dot (5th Gen) with Alexa",
    image: "https://m.media-amazon.com/images/I/61Gob-M3snL._AC_SL1000_.jpg",
    price: 49.99,
    rate: 4.7,
    category: "home gadgets",
  },
  {
    id: 26,
    title: "Smart WiFi Plug Mini (2-Pack)",
    image: "https://m.media-amazon.com/images/I/41yFX+7cO3L._AC_SX522_.jpg",
    price: 19.99,
    rate: 4.6,
    category: "home gadgets",
  },
  {
    id: 27,
    title: "iRobot Roomba 694 Robot Vacuum",
    image: "https://m.media-amazon.com/images/I/71moPp5mrmL._AC_SX679_.jpg",
    price: 179.99,
    rate: 4.5,
    category: "home gadgets",
  },
  {
    id: 28,
    title: "Kasa Smart Light Bulb, Multicolor",
    image: "https://m.media-amazon.com/images/I/61ZBUcOWUrS._AC_SX679_.jpg",
    price: 14.99,
    rate: 4.6,
    category: "home gadgets",
  },
  {
    id: 29,
    title: "Blink Mini – Compact Indoor Plug-In Smart Security Camera",
    image: "https://m.media-amazon.com/images/I/61v7scX5LjL._AC_SX522_.jpg",
    price: 34.99,
    rate: 4.5,
    category: "home gadgets",
  },
];

export default products;
